name: PerWorldChatPlus
version: ${project.version}
description: Makes chat per world and handles other chat related things. Also servers as an API for developers.
author: Shades161
website: http://dev.bukkit.org/bukkit-plugins/per-world-chat-plus/

main: com.cloudcraftgaming.perworldchatplus.PerWorldChatPlusPlugin

depend: [NovaLib]
softdepend: [Vault, Factions]

commands:
  perworldchatplus:
    description: Base command for PerWorldChatPlus.
  perworldchat:
    description: Base command for PerWorldChatPlus.
  pwcp:
    description: Base command for PerWorldChatPlus.
  pwc:
    description: Base command for PerWorldChatPlus.
  chatcolor:
    description: Command to change chat color and open ChatColor GUI.
    permission: pwcp.chat.color
  global:
    description: Short version to make a global chat message.
    permission: pwcp.global
  globalchat:
    description: Command to make a global chat message.
    permission: pwcp.global
  privatemessage:
    descripton: Command to private message another player.
    permission: pwcp.pm
  pm:
    description: Command to private message another player.
    permission: pwcp.pm
  message:
    descripton: Command to private message another player.
    permission: pwcp.pm
  msg:
    descripton: Command to private message another player.
    permission: pwcp.pm
  whisper:
    description: Command to private message another player.
    permission: pwcp.pm
  reply:
    description: Command to reply to a private message.
    permission: pwcp.pm
  r:
    description: Command to reply to a private message.
    permission: pwcp.pm
  socialspy:
    description: Command to view private messages when they are sent.
    permission: pwcp.socialspy
  ignore:
    description: Command to ignore a specfic player.
    permission: pwcp.ignore

permissions:
  pwcp.bypass:
    description: Allows a player to chat globally.
    default: op
  pwcp.bypass.ignore:
    descriptions: Prevents a player from being ignored.
    default: op
  pwcp.bypass.swear:
    description: Allows players to bypass swear filtering.
    default: op
  pwcp.bypass.ad:
    description: Allows players to bypass ad filtering.
    default: op
  pwcp.bypass.spam:
    description: Allows player to bypass spam filtering.
    default: op
  pwcp.spy:
    description: Allows players to see chats from all worlds.
    default: op
  pwcp.notify.update:
    description: Notifies the player of an update for PerWorldChatPlus.
    default: op
  pwcp.alert:
    description: Allows players to set alert words and see messages with them in it.
    default: op
  pwcp.global:
    description: Allows use of the gc or GlobalChat command.
    default: op
  pwcp.timedglobal:
    description: Allows turning on and off Timed Global Chat.
    default: op
  pwcp.mute:
    description: Allows use of muting your own chat as to reduce spam (also useful for recording videos).
    default: true
  pwcp.chat.color:
     description: Allows use of changing your own default ChatColor.
     default: op
  pwcp.chat.color.other:
    description: Allows use of changing another player's default ChatColor.
    default: op
  pwcp.pm:
    description: Allows use of private messaging commands
    default: true
  pwcp.socialspy:
    description: Allows use of the socialspy command, to view PMs as they happen.
    default: op
  pwcp.ignore:
    description: Allows use of the ignore command.
    default: true